project_id = "isfxgcfocfctwixklbvw"

[auth]
enabled = true
image = "supabase/gotrue:v2.158.1"
site_url = "https://727de735-cc70-42ed-a3f9-80607a44faa1.lovableproject.com"
additional_redirect_urls = ["https://localhost:3000"]
jwt_expiry = 3600
refresh_token_rotation_enabled = true
security_update_password_require_reauthentication = true
password_min_length = 6

[db]
enabled = true
image = "supabase/postgres:15.6.1.117"
port = 5432
shadow_port = 54320
major_version = 15

[storage]
enabled = true
image = "supabase/storage-api:v1.0.6"
file_size_limit = "50MiB"

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false
secure_password_change = false

[functions.api]
verify_jwt = false

[functions.auth]
verify_jwt = false

[functions.redirect]
verify_jwt = false